### ISSUE TITLE
서버 배포 오류 해결

### ISSUE THREAD

**Issue by hwookim** [woowa-techcamp-2021/cashbook-15#35]
bcrypt 모듈 설치가 원활하게 진행되지 않아 배포상 문제가 생김

``` shell
Error: Cannot find module '/home/ubuntu/cashbook-15/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /home/ubuntu/cashbook-15/node_modules/bcrypt/bcrypt.js
- /home/ubuntu/cashbook-15/src/controllers/auth.ts
- /home/ubuntu/cashbook-15/src/router/auth.ts
- /home/ubuntu/cashbook-15/src/router/index.ts
- /home/ubuntu/cashbook-15/src/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/ubuntu/cashbook-15/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- [x] 어떻게든 해결해 배포에 성공한다

**Comment by jigglypop** [comment]
좋네요
